# Site settings
title: Hacking Things
email: verdi@azend.org
description: My tumblelog of things.
baseurl: "/"
url: "http://blog.azend.org"

author:
  name     : 'Verdi Rodrigues-Diamond'
  email    : verdi@azend.org
  url      : http://azend.org/
  #facebook : http://facebook.com/fernando.dev
  #twitter  : http://twitter.com/nandomoreirame

github: https://github.com/azend/blog.azend.org
#disqus_shortname: "fernandomoreira"
#google_analytics: UA-52446115-1

paginate: 5
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
gems: [jekyll-paginate]
